### ISSUE TITLE
[Suggestion] Extraction of weights and their incorporation into the PyTorch model

### ISSUE THREAD

**Issue by PINTO0309** [ibaiGorordo/CREStereo-Pytorch#1]
Is it possible to share a .pickle extracted from a MegEngine model .mge?

Since the .pickle is just a freeze of the entire Python object, it may be possible to load it into PyTorch by reading the weights and saving them to an external file such as .npy after the object is recovered from the pickle.

**Comment by ibaiGorordo** [comment]
I want to look into that because I cannot train the model with my setup.

The closest thing I saw was this issue talking about the opposite, passing the weights from Pytorch to Megengine, so I guess in theory should be possible to do it.
https://github.com/MegEngine/MegEngine/issues/53

**Comment by ibaiGorordo** [comment]
Added weight conversion script and successfully tested the converted weights.

Closing the issue :slightly_smiling_face:
