### ISSUE TITLE
failed to get correct result

### ISSUE THREAD

**Issue by Tord-Zhang** [ibaiGorordo/CREStereo-Pytorch#11]
![test](https://user-images.githubusercontent.com/18326098/200522620-a80040a6-a8d8-4897-9dd6-d9464ed3d18a.jpg)

This is the result I got, which is much worse than the disparity given in README.md. Any idea why this happens? Thanks.

**Comment by ibaiGorordo** [comment]
Have you tried running the [test_model.py](https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/test_model.py) script from this repository? If so, did you change the model or the images?

**Comment by ibaiGorordo** [comment]
I see. I have only used the image from the original CREStereo repo or other image sources, but I haven't used the holopix dataset. I am not fully sure about the dataset, but according to their paper the images should be rectified already:

> "In our novel Holopix50k dataset, we present 49,368 (roughly 50k) rectified stereo image pairs collected from the mobile social media platform Holopix."

But yeah in the CREStereo paper they mention they pre-rectify to remove the negative disparity. My guess is that you could analyze the ground truth image and check where the negative disparity happens, but I have no idea about what processing they did for that. 

Do you have the images (and GT disparity) from the dataset for testing them?

**Comment by ibaiGorordo** [comment]
Maybe try something like this: https://www.andreasjakl.com/understand-and-apply-stereo-rectification-for-depth-maps-part-2/
