### ISSUE TITLE
A problem I encountered when training with pre-training models

### ISSUE THREAD

**Issue by zza1617** [ibaiGorordo/CREStereo-Pytorch#15]
When I use the model converted from crestereo_eth3d.mge for transfer learning, I encounter the following problem: model.load_state_dict(state_dict['state_dict']) KeyError: 'state_dict'.
As my laptop does not have a GPU, I commented out or deleted all "cuda" in the train.py file. Would there be any impact? The code version I am using was downloaded on November 29th, 2022.
I look forward to your prompt reply and wish you a smooth work.

**Comment by zza1617** [comment]
If I train the model from scratch without using a pre-trained model, i.e., set chk_path to None, I can obtain the trained weight file in .pth format. However, these weight files cannot be used in test.py and will result in the following error: "raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'".
RuntimeError: Error(s) in loading state_dict for CREStereo:
	Missing key(s) in state_dict: "fnet.conv1.weight", "fnet.conv1.bias", "fnet.layer1.0.conv1.weight", "fnet.layer1.0.conv1.bias", "fnet.layer1.0.conv2.weight", "fnet.layer1.0.conv2.bias", "fnet.layer1.0.downsample.0.weight", "fnet.layer1.0.downsample.0.bias", "fnet.layer1.1.conv1.weight", "fnet.layer1.1.conv1.bias", "fnet.layer1.1.conv2.weight", "fnet.layer1.1.conv2.bias", "fnet.layer1.1.downsample.0.weight", "fnet.layer1.1.downsample.0.bias", "fnet.layer2.0.conv1.weight", "fnet.layer2.0.conv1.bias", "fnet.layer2.0.conv2.weight", "fnet.layer2.0.conv2.bias", "fnet.layer2.0.downsample.0.weight", "fnet.layer2.0.downsample.0.bias", "fnet.layer2.1.conv1.weight", "fnet.layer2.1.conv1.bias", "fnet.layer2.1.conv2.weight", "fnet.layer2.1.conv2.bias", "fnet.layer2.1.downsample.0.weight", "fnet.layer2.1.downsample.0.bias", "fnet.layer3.0.conv1.weight", "fnet.layer3.0.conv1.bias", "fnet.layer3.0.conv2.weight", "fnet.layer3.0.conv2.bias", "fnet.layer3.0.downsample.0.weight", "fnet.layer3.0.downsample.0.bias", "fnet.layer3.1.conv1.weight", "fnet.layer3.1.conv1.bias", "fnet.layer3.1.conv2.weight", "fnet.layer3.1.conv2.bias", "fnet.layer3.1.downsample.0.weight", "fnet.layer3.1.downsample.0.bias", "fnet.conv2.weight", "fnet.conv2.bias", "update_block.encoder.convc1.weight", "update_block.encoder.convc1.bias", "update_block.encoder.convc2.weight", "update_block.encoder.convc2.bias", "update_block.encoder.convf1.weight", "update_block.encoder.convf1.bias", "update_block.encoder.convf2.weight", "update_block.encoder.convf2.bias", "update_block.encoder.conv.weight", "update_block.encoder.conv.bias", "update_block.gru.convz1.weight", "update_block.gru.convz1.bias", "update_block.gru.convr1.weight", "update_block.gru.convr1.bias", "update_block.gru.convq1.weight", "update_block.gru.convq1.bias", "update_block.gru.convz2.weight", "update_block.gru.convz2.bias", "update_block.gru.convr2.weight", "update_block.gru.convr2.bias", "update_block.gru.convq2.weight", "update_block.gru.convq2.bias", "update_block.flow_head.conv1.weight", "update_block.flow_head.conv1.bias", "update_block.flow_head.conv2.weight", "update_block.flow_head.conv2.bias", "update_block.mask.0.weight", "update_block.mask.0.bias", "update_block.mask.2.weight", "update_block.mask.2.bias", "self_att_fn.layers.0.q_proj.weight", "self_att_fn.layers.0.k_proj.weight", "self_att_fn.layers.0.v_proj.weight", "self_att_fn.layers.0.merge.weight", "self_att_fn.layers.0.mlp.0.weight", "self_att_fn.layers.0.mlp.2.weight", "self_att_fn.layers.0.norm1.weight", "self_att_fn.layers.0.norm1.bias", "self_att_fn.layers.0.norm2.weight", "self_att_fn.layers.0.norm2.bias", "cross_att_fn.layers.0.q_proj.weight", "cross_att_fn.layers.0.k_proj.weight", "cross_att_fn.layers.0.v_proj.weight", "cross_att_fn.layers.0.merge.weight", "cross_att_fn.layers.0.mlp.0.weight", "cross_att_fn.layers.0.mlp.2.weight", "cross_att_fn.layers.0.norm1.weight", "cross_att_fn.layers.0.norm1.bias", "cross_att_fn.layers.0.norm2.weight", "cross_att_fn.layers.0.norm2.bias", "conv_offset_16.weight", "conv_offset_16.bias", "conv_offset_8.weight", "conv_offset_8.bias". 
	Unexpected key(s) in state_dict: "epoch", "iters", "batch_size", "epoch_size", "train_loss", "state_dict", "optim_state_dict".

**Comment by T-matsubara** [comment]
Hello,

I noticed that issue #15 was recently closed. Could you please provide some information on how this issue was resolved? I'm interested in understanding the solution that was implemented. Any details or insights you could share would be greatly appreciated.
