### ISSUE TITLE
TypeError: meshgrid() got an unexpected keyword argument 'indexing'

### ISSUE THREAD

**Issue by psun-autel** [ibaiGorordo/CREStereo-Pytorch#3]
May I ask what is the torch version tested in this implementation?

**Comment by psun-autel** [comment]
Ok, torch1.10.1 works.

**Comment by ibaiGorordo** [comment]
Great! 
For future reference of anyone having the same issue:
The indexing part can be commented on most of the meshgrid calls, except for this one that would need to be substituted by the numpy version:
https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/b333d5515fae8a126f568aeeeb8bc1c35ceb2596/nets/corr.py#L121

Ref:
https://github.com/pytorch/pytorch/issues/50276

**Comment by aknurkarabay** [comment]
Hi~ I changed the pytorch version to nvcr.io/nvidia/pytorch:22.10-py3 and it helped to resolve the issue. I had it while training yolov8 model.
