### ISSUE TITLE
very nice  Pytorch implementation！can you provide the version of pytorch? or a pip requirements.txt? thank you.

### ISSUE THREAD

**Issue by If-only1** [ibaiGorordo/CREStereo-Pytorch#4]
very nice  Pytorch implementation！can you provide the version of pytorch? or a pip requirements.txt? thank you.

**Comment by ibaiGorordo** [comment]
I used Pytorch==1.11.0, but my recommendation is to use the guideline in the official Pytorch website that suits your system: https://pytorch.org/
