### ISSUE TITLE
about the arg "max_disp" when initialize the model

### ISSUE THREAD

**Issue by deephog** [ibaiGorordo/CREStereo-Pytorch#6]
I see that the default max_disp is set to be 256 but the output disparity can go way beyond, I tried the model on a pair of 4k images without any problem. I tried to search the keywords "max_disp" and "max_flow" but I can only find them in the initialization process, which means they are not actually used. So is it really not used or did I miss it? Do we need to specify the maximum disparity for the model?

Thanks

**Comment by ibaiGorordo** [comment]
Yeah, this is the same in the original repository. My guess is that they probably they modified the code from another repository and they forgot to remove that part.
