### ISSUE TITLE
about training with your script

### ISSUE THREAD

**Issue by deephog** [ibaiGorordo/CREStereo-Pytorch#8]
Hi, I noticed that you have a train.py script in your repo, but you didn't mention anything about training directly with your repo. Is it fully implemented? If not, could you kindly share what is missing and maybe I can try to add things to make it work. Thanks!

**Comment by suxingzhao** [comment]
Hi, I noticed that you have a train.py script in your repo, but you didn't mention anything about training directly with your repo. Is it fully implemented? If not, could you kindly share what is missing and maybe I can try to add things to make it work. Thanks!

**Comment by Qjizhi** [comment]
> Hi, I noticed that you have a train.py script in your repo, but you didn't mention anything about training directly with your repo. Is it fully implemented? If not, could you kindly share what is missing and maybe I can try to add things to make it work. Thanks!

Hi, I added the training code, you can refer to README.md.

**Comment by ynma-hanvo** [comment]
> > Hi, I noticed that you have a train.py script in your repo, but you didn't mention anything about training directly with your repo. Is it fully implemented? If not, could you kindly share what is missing and maybe I can try to add things to make it work. Thanks!
> 
> Hi, I added the training code, you can refer to README.md.

hi, thanks.  but can you share the dataset for training with the train.py

**Comment by Qjizhi** [comment]
> > > Hi, I noticed that you have a train.py script in your repo, but you didn't mention anything about training directly with your repo. Is it fully implemented? If not, could you kindly share what is missing and maybe I can try to add things to make it work. Thanks!
> > 
> > 
> > Hi, I added the training code, you can refer to README.md.
> 
> hi, thanks. but can you share the dataset for training with the train.py

Basically, you can use any dataset you want, just specify the paths of left, right, and disparity.
