### ISSUE TITLE
Insructions?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [ibaiGorordo/CREStereo-Pytorch#9]
Thanks for sharing this!
Can you provide instruction on how to use a pre-trained model on a pair of my own images and output a depth image?

**Comment by ibaiGorordo** [comment]
What is the shape of left_img and right_img. It is strange because the images should be resized to the eval size. Make sure you did mot modify something else.

Otherwise, I haven't used this model in a while, so not sure what might be the issue.

**Comment by ibaiGorordo** [comment]
Maybe try to modify the eval_h and eval_w to multiply of 2. Because for the flow you half the scale, and might be causing some issues.

**Comment by AiYoWeiYL** [comment]
Thank you very much! The resolution is 1242 * 375

**Comment by ibaiGorordo** [comment]
Try to change eval_h to 376 so that it is also divisible by 8 just in case.

**Comment by AiYoWeiYL** [comment]
I changed the size of the picture to 1242*376, but this error still exists. I don't know how to solve this problem.

**Comment by AiYoWeiYL** [comment]
The original size of the image is 1242*375, when I changed the size of the picture to 1240*375, it works!

**Comment by ibaiGorordo** [comment]
Nice, yeah, it seems that it needs to be divisible by 8 (I already forgot). I will modify the code slightly to show that.

**Comment by AiYoWeiYL** [comment]
The original size of the image is 1242 * 375, when I changed the size of the picture to 1240 * 375. It works!

**Comment by AiYoWeiYL** [comment]
Thank you!
